import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Input, Textarea } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { useLaloba } from "@/lib/store";
import { cn, formatRelative } from "@/lib/utils";
import { toast } from "sonner";

const TABS=["General","Apariencia","Facturación","Equipo","Conocimiento","Privacidad","Claves API","Dominios"] as const;
export const Route=createFileRoute("/settings")({component:SettingsPage});

function SettingsPage(){
 const [tab,setTab]=useState<(typeof TABS)[number]>("General");
 return <AppShell><div className="mx-auto flex max-w-5xl flex-col gap-6 px-4 py-8 md:flex-row"><aside className="flex shrink-0 gap-1 overflow-x-auto md:w-44 md:flex-col">{TABS.map((t)=><button key={t} type="button" onClick={()=>setTab(t)} className={cn("shrink-0 rounded-md px-3 py-2 text-left text-sm text-muted hover:bg-elevated hover:text-fg",tab===t&&"bg-elevated text-fg")}>{t}</button>)}</aside><div className="min-w-0 flex-1">{tab==="General"&&<General/>}{tab==="Apariencia"&&<Appearance/>}{tab==="Facturación"&&<Billing/>}{tab==="Equipo"&&<Team/>}{tab==="Conocimiento"&&<Knowledge/>}{tab==="Privacidad"&&<Privacy/>}{tab==="Claves API"&&<Keys/>}{tab==="Dominios"&&<Domains/>}</div></div></AppShell>
}
function General(){const name=useLaloba((s)=>s.displayName),email=useLaloba((s)=>s.email),workspace=useLaloba((s)=>s.workspaceName),setProfile=useLaloba((s)=>s.setProfile),setWorkspace=useLaloba((s)=>s.setWorkspace),[n,setN]=useState(name),[e,setE]=useState(email),[w,setW]=useState(workspace);return <div className="max-w-lg space-y-3"><h1 className="font-display text-2xl font-semibold">General</h1><label className="block text-xs text-muted">Nombre</label><Input value={n} onChange={(ev)=>setN(ev.target.value)}/><label className="block text-xs text-muted">Email</label><Input value={e} onChange={(ev)=>setE(ev.target.value)}/><label className="block text-xs text-muted">Workspace</label><Input value={w} onChange={(ev)=>setW(ev.target.value)}/><Button onClick={()=>{setProfile(n,e);setWorkspace(w);toast("Guardado")}}>Guardar</Button></div>}
function Appearance(){const theme=useLaloba((s)=>s.theme),setTheme=useLaloba((s)=>s.setTheme);return <div><h1 className="font-display text-2xl font-semibold">Apariencia</h1><p className="mt-2 text-sm text-muted">Tema del panel. Las apps publicadas usan su propio CSS.</p><div className="mt-4 flex flex-wrap gap-2">{(["dark","light","system"] as const).map((t)=><Button key={t} variant={theme===t?"default":"secondary"} onClick={()=>setTheme(t)}>{t==="dark"?"Oscuro":t==="light"?"Claro":"Sistema"}</Button>)}</div></div>}
function Billing(){const credits=useLaloba((s)=>s.credits),cap=useLaloba((s)=>s.creditsCap);return <div><h1 className="font-display text-2xl font-semibold">Facturación</h1><p className="mt-2 text-sm text-muted">Plan Free · créditos del mes.</p><div className="mt-4 max-w-sm rounded-xl bg-surface p-4 shadow-[var(--shadow-border)]"><p className="text-sm">Créditos</p><p className="font-display text-3xl tabular-nums">{credits} <span className="text-lg text-muted">/ {cap}</span></p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-elevated"><div className="h-full bg-primary" style={{width:`${(credits/cap)*100}%`}}/></div><Button className="mt-4" variant="secondary" onClick={()=>toast("Planes de demostración")}>Mejorar plan</Button></div></div>}
function Team(){const members=useLaloba((s)=>s.members);return <div><h1 className="font-display text-2xl font-semibold">Equipo</h1><ul className="mt-4 divide-y divide-border rounded-xl bg-surface shadow-[var(--shadow-border)]">{members.map((m)=><li key={m.id} className="flex items-center justify-between px-4 py-3 text-sm"><div><p>{m.name}</p><p className="text-xs text-muted">{m.email}</p></div><span className="text-muted">{m.role}</span></li>)}</ul><Button className="mt-4" variant="secondary" onClick={()=>toast("Invitación (demo)")}>Invitar</Button></div>}
function Knowledge(){const knowledge=useLaloba((s)=>s.knowledge),setKnowledge=useLaloba((s)=>s.setKnowledge),[v,setV]=useState(knowledge);return <div className="max-w-lg"><h1 className="font-display text-2xl font-semibold">Conocimiento</h1><p className="mt-2 text-sm text-muted">Instrucciones que Laloba aplica a todos los proyectos del workspace.</p><Textarea className="mt-4 min-h-40" value={v} onChange={(e)=>setV(e.target.value)}/><Button className="mt-3" onClick={()=>{setKnowledge(v);toast("Conocimiento actualizado")}}>Guardar</Button></div>}
function Privacy(){const [train,setTrain]=useState(false);return <div className="max-w-lg space-y-4"><h1 className="font-display text-2xl font-semibold">Privacidad</h1><label className="flex items-center justify-between gap-4 rounded-xl bg-surface p-4 shadow-[var(--shadow-border)]"><span className="text-sm">Permitir entrenar modelos con mis proyectos</span><Switch checked={train} onCheckedChange={setTrain}/></label><p className="text-sm text-muted">Los datos viven en este navegador. No hay cuentas en Laloba demo.</p></div>}
function Keys(){const keys=useLaloba((s)=>s.apiKeys),add=useLaloba((s)=>s.addApiKey),revoke=useLaloba((s)=>s.revokeApiKey);return <div><h1 className="font-display text-2xl font-semibold">Claves API</h1><Button className="mt-4" size="sm" onClick={()=>{const name=window.prompt("Nombre de la clave","Local");if(name){const k=add(name);toast(`Creada ${k.prefix}…`)}}}>Nueva clave</Button><ul className="mt-4 space-y-2">{keys.map((k)=><li key={k.id} className="flex items-center justify-between rounded-lg bg-surface px-3 py-2 text-sm"><div><p>{k.name}</p><p className="font-mono text-xs text-muted">{k.prefix}… · {formatRelative(k.createdAt)}</p></div><Button size="sm" variant="ghost" onClick={()=>revoke(k.id)}>Revocar</Button></li>)}</ul></div>}
function Domains(){return <div className="max-w-lg"><h1 className="font-display text-2xl font-semibold">Dominios</h1><p className="mt-2 text-sm text-muted">Los proyectos publicados usan slug.laloba.app. Añade un dominio propio desde el diálogo Publicar de cada app.</p><ul className="mt-4 space-y-2 text-sm"><li className="rounded-lg bg-surface px-3 py-2">laloba.app · workspace</li><li className="rounded-lg bg-surface px-3 py-2">cafe-lobo.laloba.app · Café Lobo</li></ul></div>}
