import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip as RTooltip, XAxis, YAxis } from "recharts";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input, Textarea } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { useLaloba } from "@/lib/store";
import type { Project } from "@/lib/types";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

const TOOLS=["Analytics","Cloud","IA","Pagos","Conectores","Seguridad","SEO","Ajustes"] as const;
type Tool=(typeof TOOLS)[number];
const visits=[{d:"Lun",v:120,p:80},{d:"Mar",v:180,p:110},{d:"Mié",v:90,p:70},{d:"Jue",v:240,p:160},{d:"Vie",v:310,p:200},{d:"Sáb",v:150,p:90},{d:"Dom",v:80,p:40}];

export function MorePanel({project}:{project:Project}) {
 const [tool,setTool]=useState<Tool>("Analytics");
 return <div className="flex h-full min-h-0"><aside className="w-44 shrink-0 overflow-y-auto border-r border-border p-2">
  {TOOLS.map((t)=><button key={t} type="button" onClick={()=>setTool(t)} className={cn("mb-0.5 w-full rounded-md px-2 py-2 text-left text-sm text-muted hover:bg-elevated hover:text-fg",tool===t&&"bg-elevated text-fg")}>{t}</button>)}
 </aside><div className="min-w-0 flex-1 overflow-y-auto p-5">
  {tool==="Analytics"&&<Analytics/>}{tool==="Cloud"&&<Cloud/>}{tool==="IA"&&<AiSpend/>}{tool==="Pagos"&&<Payments/>}{tool==="Conectores"&&<ProjectConnectors/>}{tool==="Seguridad"&&<Security/>}{tool==="SEO"&&<Seo project={project}/>} {tool==="Ajustes"&&<ProjectSettings project={project}/>}
 </div></div>;
}
function Analytics(){return <div><h2 className="font-display text-lg font-semibold">Analytics</h2><p className="text-sm text-muted">Visitantes de los últimos 7 días (demo).</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Stat label="Visitantes" value="1.170"/><Stat label="Vistas" value="3.482"/><Stat label="Tasa publicación" value="64%"/></div><div className="mt-6 h-56"><ResponsiveContainer width="100%" height="100%"><LineChart data={visits}><CartesianGrid stroke="var(--color-border)" strokeDasharray="3 3"/><XAxis dataKey="d" stroke="var(--color-muted)" fontSize={12}/><YAxis stroke="var(--color-muted)" fontSize={12}/><RTooltip/><Line type="monotone" dataKey="v" stroke="var(--color-steel)" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div><div className="mt-6 h-40"><ResponsiveContainer width="100%" height="100%"><BarChart data={visits}><XAxis dataKey="d" stroke="var(--color-muted)" fontSize={12}/><Bar dataKey="p" fill="var(--color-primary)" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-elevated p-3 shadow-[var(--shadow-border)]"><p className="text-xs text-muted">{label}</p><p className="font-display text-2xl tabular-nums">{value}</p></div>}
function Cloud(){const [tab,setTab]=useState("Base de datos");const tabs=["Base de datos","Usuarios","Storage","Jobs","Functions","Secrets","Logs"];return <div><h2 className="font-display text-lg font-semibold">Laloba Cloud</h2><div className="mt-3 flex flex-wrap gap-1">{tabs.map((t)=><button key={t} type="button" onClick={()=>setTab(t)} className={cn("rounded-full px-3 py-1 text-xs text-muted hover:bg-elevated",tab===t&&"bg-elevated text-fg")}>{t}</button>)}</div>{tab==="Base de datos"&&<table className="mt-4 w-full text-left text-sm"><thead className="text-muted"><tr><th className="py-2 font-medium">Tabla</th><th>Filas</th></tr></thead><tbody>{[["profiles",128],["projects",46],["invoices",19]].map(([n,r])=><tr key={String(n)} className="border-t border-border"><td className="py-2 font-mono text-xs">{n}</td><td className="tabular-nums">{r}</td></tr>)}</tbody></table>}{tab==="Usuarios"&&<p className="mt-4 text-sm text-muted">128 usuarios autenticados · email + Google.</p>}{tab==="Storage"&&<p className="mt-4 text-sm text-muted">2 buckets · 340 MB usados de 1 GB.</p>}{tab==="Jobs"&&<p className="mt-4 text-sm text-muted">Ningún job programado. Crea uno para informes nocturnos.</p>}{tab==="Functions"&&<p className="mt-4 text-sm text-muted">edge/send-invoice · edge/stripe-webhook</p>}{tab==="Secrets"&&<ul className="mt-4 space-y-2 text-sm"><li className="flex justify-between rounded-md bg-elevated px-3 py-2"><span>STRIPE_KEY</span><span className="text-muted">•••• 4k2a</span></li><li className="flex justify-between rounded-md bg-elevated px-3 py-2"><span>RESEND_KEY</span><span className="text-muted">•••• 9q1c</span></li></ul>}{tab==="Logs"&&<pre className="mt-4 overflow-auto rounded-lg bg-elevated p-3 font-mono text-xs text-muted">{`12:04:21 GET / 200 42ms
12:04:33 POST /api/invoice 201 118ms
12:05:02 GET /auth/session 200 11ms`}</pre>}</div>}
function AiSpend(){return <div><h2 className="font-display text-lg font-semibold">IA de la app</h2><p className="text-sm text-muted">Grok para funciones de tu producto. Este mes: 12.400 tokens.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Stat label="Tokens" value="12.4k"/><Stat label="Coste estimado" value="0,86 €"/></div><Button className="mt-4" variant="secondary" onClick={()=>toast("Límite guardado")}>Tope 5 € / mes</Button></div>}
function Payments(){return <div><h2 className="font-display text-lg font-semibold">Pagos</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{["Stripe","Paddle"].map((n)=><article key={n} className="rounded-lg bg-elevated p-4 shadow-[var(--shadow-border)]"><h3 className="font-medium">{n}</h3><p className="mt-1 text-sm text-muted">Conecta para cobrar en tu app.</p><Button className="mt-3" size="sm" variant="secondary" onClick={()=>toast(`${n} · demo`)}>Conectar</Button></article>)}</div></div>}
function ProjectConnectors(){const connectors=useLaloba((s)=>s.connectors);const toggle=useLaloba((s)=>s.toggleConnector);return <div><h2 className="font-display text-lg font-semibold">Conectores del proyecto</h2><ul className="mt-3 space-y-2">{connectors.filter((c)=>c.connected).map((c)=><li key={c.id} className="flex items-center justify-between rounded-lg bg-elevated px-3 py-2"><span className="text-sm">{c.name}</span><Switch checked={c.connected} onCheckedChange={()=>toggle(c.id)}/></li>)}</ul></div>}
function Security(){const findings=[{id:1,sev:"medio",title:"Formulario sin CSRF",ok:false},{id:2,sev:"bajo",title:"Cabecera CSP ausente",ok:false},{id:3,sev:"info",title:"Dependencias al día",ok:true}];return <div><h2 className="font-display text-lg font-semibold">Seguridad</h2><ul className="mt-3 space-y-2">{findings.map((f)=><li key={f.id} className="flex items-center justify-between rounded-lg bg-elevated px-3 py-2 text-sm"><span>{f.title}</span><span className="text-xs text-muted">{f.ok?"ok":f.sev}</span></li>)}</ul><Button className="mt-4" variant="secondary" onClick={()=>toast("Escaneo lanzado")}>Escanear de nuevo</Button></div>}
function Seo({project}:{project:Project}){const update=useLaloba((s)=>s.updateProject);return <div className="max-w-lg space-y-3"><h2 className="font-display text-lg font-semibold">SEO y búsqueda IA</h2><label className="block text-xs text-muted">Título</label><Input value={project.seoTitle??project.name} onChange={(e)=>update(project.id,{seoTitle:e.target.value})}/><label className="block text-xs text-muted">Descripción</label><Textarea value={project.seoDescription??""} onChange={(e)=>update(project.id,{seoDescription:e.target.value})}/><Button onClick={()=>toast("Metadatos guardados")}>Guardar</Button></div>}
function ProjectSettings({project}:{project:Project}){const update=useLaloba((s)=>s.updateProject);const knowledge=useLaloba((s)=>s.knowledge);const setKnowledge=useLaloba((s)=>s.setKnowledge);return <div className="max-w-lg space-y-4"><h2 className="font-display text-lg font-semibold">Ajustes del proyecto</h2><label className="block text-xs text-muted">Nombre</label><Input value={project.name} onChange={(e)=>update(project.id,{name:e.target.value})}/><label className="block text-xs text-muted">Visibilidad</label><div className="flex gap-2">{(["private","workspace","public"] as const).map((v)=><Button key={v} size="sm" variant={project.visibility===v?"default":"secondary"} onClick={()=>update(project.id,{visibility:v})}>{v==="private"?"Privado":v==="workspace"?"Workspace":"Público"}</Button>)}</div><label className="block text-xs text-muted">Dominio</label><Input placeholder="app.tudominio.com" value={project.customDomain??""} onChange={(e)=>update(project.id,{customDomain:e.target.value})}/><label className="block text-xs text-muted">Conocimiento</label><Textarea value={project.knowledge||knowledge} onChange={(e)=>{update(project.id,{knowledge:e.target.value});setKnowledge(e.target.value)}}/><p className="text-xs text-muted">Git: conecta GitHub desde Conectores para sincronizar.</p></div>}
